-- AlterTable
ALTER TABLE "NutritionPlan" ALTER COLUMN "startDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "endDate" SET DEFAULT NOW() + INTERVAL '30 days';

-- AlterTable
ALTER TABLE "WorkoutPlan" ALTER COLUMN "startDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "endDate" SET DEFAULT NOW() + INTERVAL '30 days';
